spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/user_db
    username: xcode
    password: 123
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: 'update'